Repository buildit/buildit, pull requests merged in 2019-03, with the labels that each got.

#198 Misc dev dependency updates
  gulp/.babelrc
  package-lock.json
  package.json
Labels: enhancement, greenkeeper

#184 Web 219
  .babelrc
  babel.config.js
  docs/DECISIONLOG.md
  jest.config.js
  package-lock.json
  package.json
  src/scripts/.babelrc
  src/scripts/heroAnimation/__tests__/hero.test.js
  src/scripts/heroAnimation/__tests__/utils.test.js
  src/scripts/heroAnimation/hero.js
  src/scripts/heroAnimation/utils.js
  src/scripts/main.js
  templates/partials/scripts-footer.hbs
Labels: enhancement

#220 Header fixes
  src/sass/style.scss
  src/scripts/heroAnimation/hero.js
Labels: bug
